services:
  joe-and-alex:
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4096M
    environment:
      ADMIN_PASSWORD: alex&joe2026
      NVIDIA_VISIBLE_DEVICES: void
      TZ: America/Chicago
    group_add:
      - 568
    image: forgejo.int.aafoods.com/ajthom90/joe-and-alex:2.0.0
    ports:
      - mode: ingress
        protocol: tcp
        published: 42698
        target: 3000
    privileged: false
    pull_policy: always
    restart: unless-stopped
    stdin_open: false
    tty: false
    volumes:
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: false
        source: /mnt/AAPOOL/apps/joe-and-alex
        target: /data
        type: bind
volumes: {}
